### ISSUE TITLE
USAID Monthly Integrated Dashboard | Using captions to detail filter selection

### ISSUE THREAD

**Issue by ChristaOost** [USAID-SA-SI/non-MER#12]
Update this dashboard to mimic what was done in the MER C&T workbook

**Comment by gsarfaty** [comment]
- [x] MER and non MER
- [x] CROSS-CUTTING
- [x] TESTING
- [x] INDEX
- [x] HIVSS
- [x] EID
- [x] LINKAGE
- [x] RETENTION
- [x] EMA/LMA
- [x] DECANTING
- [x] CCMDD
- [x] TLD
- [x] VL
- [x] CD4
- [x] CrAG
- [x] IPC
- [x] COVID-19
- [x] TPT

**Comment by gsarfaty** [comment]
completed for Nov dash
