### ISSUE TITLE
USAID Monthly Integrated Dashboard | Add linkage to HIVSS table

### ISSUE THREAD

**Issue by ChristaOost** [USAID-SA-SI/non-MER#13]
Tab 4.3 HIV_SS Cascade over time add yield. This request was made in the context of targeted testing and wanting to ascertain whether in Districts where this has been implemented it has resulted in higher yield over time. Calculation = Total HIVSS clients screened / New positive confirmed HIVSS

**Comment by gsarfaty** [comment]
linkgage and yield added to table
