### ISSUE TITLE
USAID Monthly Integrated Dashboard | Build out of the Facility Performance Table

### ISSUE THREAD

**Issue by ChristaOost** [USAID-SA-SI/non-MER#15]
Request from Zandile who extracts the data manually from Tableau to do the following: Build out 1.2 CROSS-CUTTING FACILITY PERFORMANCE TABLE to include Community, Siyenza vs non-Siyenza & current values for: HTS_TST, HTS_TST_POS, TX_NEW, and TX_CURR. The numerator and denominator for yield, linkage and end point for TX_CURR_28 makes it easier to interpret these % values correctly and identify poorest facilities by district on various metrics. She wants, for example, to be able to identify facilities with high linkage, but who only found 2 positives and linked these 2 to care, but who normally reports higher volumes of clients.

**Comment by gsarfaty** [comment]
added to nov dash
