### ISSUE TITLE
USAID SA Weekly Dashboard | Build out the Facility Performance Table

### ISSUE THREAD

**Issue by ChristaOost** [USAID-SA-SI/non-MER#16]
Request from Zandile who extracts the data manually from Tableau to do the following: Build out 1.2 CROSS-CUTTING FACILITY PERFORMANCE TABLE to include Community, Siyenza vs non-Siyenza & current values for: HTS_TST, HTS_TST_POS, TX_NEW, and TX_CURR. The numerator and denominator for yield, linkage and end point for TX_CURR_28 makes it easier to interpret these % values correctly and identify poorest facilities by district on various metrics. She wants, for example, to be able to identify facilities with high linkage, but who only found 2 positives and linked these 2 to care, but who normally reports higher volumes of clients. 

The weekly data is used to monitor partner activity, volumes and resources used and not for patient management.

**Comment by gsarfaty** [comment]
weekly retired
